Specify context for missing required files
```
Error: Required file 'missing-file.php' doesn't exist (from project's
wp-cli.yml).
```

```
Error: Required file 'baz.php' doesn't exist (from global config.yml).
```